// export const LOGIN_USERS = 'LOGIN_USERS'
// export const REGISTER_USERS = 'REGISTER_USERS'

export const GET_COMICS = 'GET_COMICS'
export const GET_DETAILCOMICS = 'GET_DETAILCOMICS'
export const GET_DETAILEPISODES = 'GET_DETAILEPISODES'
export const GET_FAVORITES = 'GET_FAVORITES'


export const GET_USERPROFILE = 'GET_USERPROFILE'

export const GET_MYWEBTOONS = 'GET_MYWEBTOONS'